name: spice_data
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - cmocean
  - netcdf4
  - dask
  - scipy
  - tqdm
  - simplekml
  - pip
  - pip:
      - copernicusmarine
      - erddapy
      - gsw
      - seawater
      - cool-maps
      - thermohalinesteps
      - cmcrameri
