# Configuration file to set x and y lims for TS diagrams
absolute_salinity:
  title: Absolute Salinity
  min:
  max:
conservative_temperature:
  title: Conservative Temperature
  min:
  max:
depth:
  title: Depth
  min:
  max:
