# Configuration file to set x and y lims for TS diagrams
salinity:
  title: Absolute Salinity
  min:
  max:
temperature:
  title: Conservative Temperature
  min:
  max:
depth:
  title: Depth
  min:
  max:
